### ISSUE TITLE
Selecting default simulated device on ios

### ISSUE THREAD

**Issue by morious** [Microsoft/vscode-cordova#174]
Hi,
I am trying to find a way to tell visual studio code debugger which default device to simulate on when running on a simulator.
I am using a 'launch' request.

Thx!

**Comment by MSLaguana** [comment]
Just to clarify, when you refer to the simulator do you mean the iOS simulator / android emulator, or do you mean the browser simulation?

If you mean the iOS simulator or android emulator, then you can use the `"target"` field in the launch.json entry to specify the kind of emulator to use. Instead of `"target": "emulator"`, you can use an identifier that you could pass to the cordova CLI's `--target=<identifier>` parameter, such as `Nexus_5_API_23_x86` or `iPhone-6` (assuming you have the appropriately named emulators)

If you are referring to the browser simulation, then we do not currently support launching the simulation as a specific device, but you may modify it at runtime using the plugin controls and then refresh the app.

**Comment by morious** [comment]
@MSLaguana - Thank you!
I was referring to the iOS simulator. 
I replaced "target": "emulator" with "target": "iPad-2, 9.3" to achieve what i was going for and it worked - Thank you!
