### ISSUE TITLE
Cannot Inspect Element when Simulating Android in Browser

### ISSUE THREAD

**Issue by SirusDoma** [Microsoft/vscode-cordova#189]
I use Visual Studio Code to test my cordova application, I choose to debug the application in browser via "Simulate Android in Browser" option to make it quick and take advantage of livereload.

However, when chrome launch, I cannot open Inspector, if I try to open it, the chrome immediately close without any errors, there is no clues on vscode as well.

Any idea?

**Comment by MSLaguana** [comment]
When you launch "simulate android in browser" we attach to the browser for debugging. Since chrome only permits one debugger to attach at a time, if you open the chrome devtools then it disconnects our debugger, and we essentially assume that means debugging is over, so we tear everything down which also closes the window.

If you do not want to use vscode's debugging capabilities, then you can use [cordova simulate](https://github.com/microsoft/cordova-simulate) directly, which is the same package we use for the simulation.

**Comment by SirusDoma** [comment]
I see, I don't find this explanation on the README of this repository.
Might good idea to put in there, just a suggestion tho.

Anyway, I actually kind of interested to use vscode debugging tools, but I want to inspect html elements as well. is it possible within vscode? if not, is there any plan to support this? (maybe something like visual studio did?)

Oh and one small question; is livereload works on real device?
Thanks for your reply

**Comment by MSLaguana** [comment]
Apologies for the delay in responding.

Currently it's very difficult to extend vscode's debugging UI to handle things like DOM inspection, so we don't have any plans there in the near future. Regarding livereload on actual devices, we don't support that out of the box. There are some libraries which aim to support that such as browsersync I think, but I haven't tried them out recently.
