### ISSUE TITLE
Ionic Serve with CLI-Window

### ISSUE THREAD

**Issue by GeorgBraunHM** [Microsoft/vscode-cordova#190]
Hello,
thanks a lot for this wonderfull extension.
I am developing Ionic 2 Apps and I use `ionic serve` a lot within the integrated terminal window of VSCode. The nice thing with it is that I can see the live-reload-messages and enable/disable consolelogs on the fly. The drawback with that is that I cannot attach the VSCode-Debugger to it.

Recently, I have been able to use the "Serve to the browser (ionic serve)" command from the vscode-cordova extension. The big advantage is the great debugger experience. The drawback is that I don't get the live-reload-messages any longer when a source file has changed. 

Therefore, is it possible to 
1. either display the live-reload-messages when using "Serve to the browser (ionic serve)" from vscode-cordova, or
2. add the possibility to attach to a running "ionic serve" (I am not sure if remote debugging can be enabled on chrome when using ionic serve)?

Many thanks!

**Comment by MSLaguana** [comment]
If you are comfortable running `ionic serve` yourself, you can use https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome to attach to an existing instance of chrome. You can even have one project use both options: If you add an appropriate entry in your `launch.json` file you can have one option attach to chrome using that extension, and another launch target use our extension to launch and attach to a device/emulator (or run ionic serve itself).

As for exposing the messages; that's something that we can look into. Working out the right balance of verbosity can be difficult since vscode doesn't give a lot of ways to provide information without it getting cluttered. @panarasi what are your thoughts here?
