### ISSUE TITLE
Does this work with ReactNative?

### ISSUE THREAD

**Issue by jordwalke** [Microsoft/vscode-cordova#24]
ReactNative uses JSC on both iOS and Android, and I believe the JSC for iOS would work with ios-webkit-debug-proxy.

1. Does this work?
2. Have you supported showing profiling information from JSC?

If it doesn't yet work, I think it would be a great addition to this toolchain.

**Comment by MSLaguana** [comment]
We don't support attaching to react native applications at the moment. You are correct that it is possible to attach to the JSC on iOS devices, but it's done in a slightly different way to what we expect for cordova, so it won't work out-of-the-box here. I also don't believe that it is possible to attach to the JSC on Android without making some changes to the cpp code in the application.

As for your second question, we do not currently grab profiling information from the device. Debug adapters for vscode have limited ability to control the UI of vscode, so it's not clear how we could present that kind of information well unfortunately.

**Comment by axemclion** [comment]
@jordwalke We are working on an alternate way to connect and debug to ReactNative. More details [here](http://blog.nparashuram.com/2016/02/writing-custom-debugger-for-reactnative.html). We also have a [prototype](http://taco.tools/vscode/rn.html).
We basically create a node process instead of using Chrome and attach debugging to it. At the moment, we are waiting for [a pull request[(https://github.com/facebook/react-native/pull/5683) to be accepted for our extension to work. We plan to talk about the extension at ReactConf.
