### ISSUE TITLE
Debug ionic 2 with typescript

### ISSUE THREAD

**Issue by lokinfey** [Microsoft/vscode-cordova#25]
I want to know how to set debug in my ionic 2 project when I use typescript

**Comment by MSLaguana** [comment]
You need to make sure that you produce source maps as part of your build process. The specifics of this will depend on exactly how you build your project, but for a plain `ionic start myProject -v2` project you need to do something like the following:

* `npm install source-map-loader strip-sourcemap-loader`
* Go into your `webpack.config.js` file and enable sourcemaps by adding a `devtool: 'source-map'` entry to your module.exports
* Also in `webpack.config.js` add `output.devtoolModuleFilenameTemplate: 'file:///[absolute-resource-path]'` to your exports so that the source maps refer to the original sources by absolute path
* Make sure that the bundle file does not include any other source maps by adding an export like

```
module: {
    loaders: [
        {
            test: /\.js$/,
            loader: 'strip-sourcemap'
        }
    ]
}
```
* Optional bonus step: after building, double check that there is exactly one `//# sourceMappingURL` in the bundle file, and it appears right at the end. When I was testing this out I found that one of the angular sources had a source map comment that did not start at the beginning of a line, and thus strip-sourcemap didn't remove it

At this point you should be able to debug your app with our extension. However a word of warning: When I was testing this out on the starter ionic v2 app I found that the sourcemaps were off by a couple of lines, so breakpoints set in the original code were hit a couple of lines later in the bundle file.

**Comment by lokinfey** [comment]
my webpack.config.js like this

var path = require('path');


module.exports = {
  devtool:['source-map'],
  entry: [
    path.normalize('es6-shim/es6-shim.min'),
    'reflect-metadata',
    'web-animations.min',
    path.normalize('zone.js/dist/zone-microtask'),
    path.resolve('app/app')
  ],
  
  output: {
    path: path.resolve('www/build/js'),
    filename: 'app.bundle.js',
    pathinfo: true, // show module paths in the bundle, handy for debugging
    devtoolModuleFilenameTemplate: 'app'
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loader: 'awesome-typescript',
        query: {
          doTypeCheck: false,
          useWebpackText: true
        },
        include: path.resolve('app'),
        exclude: /node_modules/
      },
    //   {
    //     test: /\.js$/,
    //     include: path.resolve('node_modules/angular2'),
    //     loader: 'strip-sourcemap'
    //   }
    ],
    noParse: [
      /es6-shim/,
      /reflect-metadata/,
      /web-animations/,
      /zone\.js(\/|\\)dist(\/|\\)zone-microtask/
    ]
  },
  resolve: {
    alias: {
      'ionic': 'ionic-framework',
      'web-animations.min': path.normalize('ionic-framework/js/web-animations.min')
    },
    extensions: ['', '.js',".ts"]
  }
};

This is my folder include I want to debug ts file . I follow your step . But I can not debug with vs code . Something wrong about that
<img width="215" alt="2016-01-30 9 34 45" src="https://cloud.githubusercontent.com/assets/4607663/12692640/f6102438-c734-11e5-98f8-270913d2e3a4.png">

**Comment by MSLaguana** [comment]
You have `devtool: ['sourcemap']` instead of `devtool: 'sourcemap'`. If you change that, then you should see `www/build/js/app.bundle.js.map` created as part of your build.

Once that is set up, you need to configure your source maps to refer to files correctly. Right now you specify `devtoolModuleFilenameTemplate: 'app'`, but that should be `devtoolModuleFilenameTemplate: 'file:///[absolute-resource-path]'`. After setting this, when you next compile you should see the `app.bundle.js.map` file starting with a bunch of files specified via absolute paths.

The last thing to do is to make sure that the bundle source refers to the sourcemap. If you open up `www/build/js/app.bundle.js` and search for `sourceMappingURL` there should be only one right at the end. If there are others, then you will need to remove them. One way to do that is with the `strip-sourcemaps` loader, part of which you seem to have commented out. When I was testing this, I added a new loader to the end of the loaders list that was just 

```
{
    test: /\.js$/,
    loader: 'strip-sourcemap'
}
```

Once you make sure that there is only one `sourceMappingURL` specified for your bundle, then you should be able to set breakpoints in your code. One part that I'm not sure about is whether the mappings will work directly for the typescript sources, or if they will work for the javascript generated from the typescript.

**Comment by lokinfey** [comment]
I try it , but I can not see app.bundle.js.map

**Comment by lokinfey** [comment]
I repair my webpack.config.js

var path = require('path');


module.exports = {
  devtool:['source-map'],
  entry: [
    path.normalize('es6-shim/es6-shim.min'),
    'reflect-metadata',
    'web-animations.min',
    path.normalize('zone.js/dist/zone-microtask'),
    path.resolve('app/app')
  ],
  
  output: {
    path: path.resolve('www/build/js'),
    filename: 'app.bundle.js',
    pathinfo: false, // show module paths in the bundle, handy for debugging
    devtoolModuleFilenameTemplate: 'file:///www/build/js/'
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loader: 'awesome-typescript',
        query: {
          doTypeCheck: false,
          useWebpackText: true
        },
        include: path.resolve('app'),
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        include: path.resolve('node_modules/angular2'),
        loader: 'strip-sourcemap'
      },
      {
          test: /\.js$/,
          loader: 'strip-sourcemap'
      }
    ],
    noParse: [
      /es6-shim/,
      /reflect-metadata/,
      /web-animations/,
      /zone\.js(\/|\\)dist(\/|\\)zone-microtask/
    ]
  },
  resolve: {
    alias: {
      'ionic': 'ionic-framework',
      'web-animations.min': path.normalize('ionic-framework/js/web-animations.min')
    },
    extensions: ['', '.js',".ts"]
  }
};

When I use cmd+shitf+B

I can not create any www/build/js/app.bundle.js.map

**Comment by MSLaguana** [comment]
If you are building an ionic app you can't use the default build task in vscode-cordova which runs `cordova build`. Instead you will need to run `ionic build` to run all of the extra ionic steps in the process. You can configure a task in vscode following https://code.visualstudio.com/Docs/editor/tasks, but it may be easier to just run it on the command line yourself.

**Comment by lokinfey** [comment]
ok !! Thx ! I forget that . I run ionic build all it is right .

**Comment by beachygreg** [comment]
A not to anyone else reading this. You now only need to change the following to generate source map files.
tsconfig.js:
  `  "sourceMap": true`
webpack.config.js:
    `module.exports.devtool:` 'source-map'`

**Comment by neilyoung** [comment]
This is all completely fucked up and doesn't work. No matter what you config where...:( "A new way of code edtiting"... Well, looks like the old
