### ISSUE TITLE
execution will not stop on breakpoint or debugger

### ISSUE THREAD

**Issue by iliran11** [Microsoft/vscode-cordova#256]
activating breakpoints or writing 'debugger' will not stop the execution of the program when deploying my program to android emulator.

- my enviroment:

cordova: 6.5.0
Visual Studio Code:  1.10.2
Android Emulator: Nexus S API 23.
OS: Windows 7

- created a simple cordova project using those 2 commands:

```
cordova create cordovatest
cordova platform add android --save
```

- used "run android on emulator" launch configuration:

```
            "name": "Run Android on emulator",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "emulator",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceRoot}",
            "ionicLiveReload": false

```

- screenshot, hope it helps:

![image](https://cloud.githubusercontent.com/assets/24987188/23790920/c27e9b06-0589-11e7-8077-0da2e27da6f2.png)

**Comment by vladimir-kotikov** [comment]
@iliran11, thanks for the report, we'll try to take a look shortly and get back to you.

**Comment by vladimir-kotikov** [comment]
@iliran11, sorry for late response.

I'm afraid that this behavior is expected - you're not getting debugger stopped on these breakpoints because at the time when these lines are executed the debugger is not attached yet. This happens because searching for active webviews and then connecting to the one we want to debug takes some time.

To confirm this simply put breakpoint into code that executes on some user interaction (e.g. on button click) and then click that button - debugger will stop on this breakpoint because at this time we already connected.

**Comment by navs007** [comment]
having the same issue but its a full fledged project and i know the breakpoint is hit on chrome://inspect and not in visual studio code

**Comment by SounD120** [comment]
Hi @navs007 . Thanks for reaching us. Could you please create a new issue for your specific case?

**Comment by navs007** [comment]
> Hi @navs007 . Thanks for reaching us. Could you please create a new issue for your specific case?

https://github.com/microsoft/vscode-cordova/issues/587
