### ISSUE TITLE
Get rid of ctrl+shift+b as default shortcut to build cordova

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode-cordova#28]
Instead let the user chose wich keyboard shortcut she or he will use to build cordova apps.

**Comment by egamma** [comment]
You can customize the short cut. You want to customize the binding for `workbench.action.tasks.build` as shown below (see the [customize keybindings doc](https://code.visualstudio.com/docs/customization/keybindings) for details).

```json
[
    { "key": "ctrl+shift+b",          "command": "workbench.action.tasks.build" }
]
```

**Comment by NCC1701M** [comment]
Yes I know, but it was standard before cordova so why has every user to customize standard behaviour?

**Comment by egamma** [comment]
Now, I see 

The cordova extension takes over the keybinding for `workbench.action.tasks.build`:

```json
{ "key": "ctrl+shift+b",          "command": "cordova.build" },
```
I agree, whenever possible an extension should not take over an established key binding.

**Comment by meenakb** [comment]
Thanks for the feedback! We will incorporate this in our future update.

**Comment by nisheetjain** [comment]
@NCC1701M @egamma we concluded that ctrl+shift+b means build and that's what "build" means for a Cordova project. It's a commonly used key binding which will go unused otherwise (while we try to invest and set new keybinding for user).

**Comment by egamma** [comment]
The issue is that a user can work in different workspaces and only some of them include Cordova projects others can have configured VS Code tasks. Once a user installs the Cordova extension, then the keybinding is globally defined. This breaks the behaviour for the user's in workspaces which are not cordova projects.

Here are some options:

- check in the `cordova.build` command whether the workspace is a cordova project. If this is not the case then you excute the `workbench.action.task.build` command using `vscode.commands.executeCommand()`.
- provide a command that generates a task.json file that invokes the cordova build utility. In this way the user can still invoke the cordova build using a task and the key binding is still valid.

**Comment by nisheetjain** [comment]
pointed noted :) . Agree we should fix this. I like both suggestions.

**Comment by meenakb** [comment]
Following a discussion with @nisheetjain and @subhagpo, we have decided not to use ctrl+shift+b as the shortcut for Cordova build. 

We will henceforth use "f6" as the shortcut for Cordova build.
