### ISSUE TITLE
Breaks compilation if typings are part of package.json as @types/..

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode-cordova#299]
I have cordova typings added to a project via package.json:
```json
  "devDependencies": {
    "@types/cordova": "^0.0.34"
  }
```
The problem is that this extension creates a separate typings/ folder with cordova typing files which leads to "duplicate identifier" compiler errors. I currently can't use the extension and have to disable it because of that.

**Comment by vladimir-kotikov** [comment]
@letmaik, thanks for reporting. Just a quick question - does your project has `tsconfig.json` in the root folder? I'm asking because I'm trying to figure out what would be the best indicator to use to skip own typings installation. We currenly look for `tsconfig.json` to decide whether to install typings for plugins or not so I think we might just do the same for cordova typings as well.
