### ISSUE TITLE
Error when try to run a page with materialize framework

### ISSUE THREAD

**Issue by Marcospdsr** [Microsoft/vscode-cordova#308]
hi i try to run a page with materialize but was return this message:
TypeError: Cannot read property 'left' of undefined

Can you help me?

**Comment by vladimir-kotikov** [comment]
@Marcospdsr, where are you seing this message? Is there a stack trace or more detailed error message available? 

Also if you're talking about [materialize](https://github.com/Dogfalo/materialize) then your problem looks more like a general JavaScript issue that is more related to your code rather than to this extension. To exclude this you might want to try debug your code using browser instead of the extension and see if the problem still occurs.

**Comment by vladimir-kotikov** [comment]
Closing this as unrelated to the extension
