### ISSUE TITLE
Cannot close cordova-simulate window

### ISSUE THREAD

**Issue by lhrolim** [Microsoft/vscode-cordova#338]
Hi, 

I´ve setup vscode-cordova today and I´m my development workflow I´d like to simply use chrome to debug the code while keeping vscode as the editor.

However If I close the "cordova-simulate" tab on the editor I cannot refresh the browser any more since the deviceready events are no longer fired.

Keeping the tab opened works, but reduces considerably the code pane, making development a hassle.

Is there a workaround for this?

My project is using cordova 7.1.0 and ionic 1

**Comment by jwargo** [comment]
If you run ionic serve from the terminal, it will keep live reload running and not open Cordova Simulate.

**Comment by lhrolim** [comment]
@jwargo I´ve never really used ionic serve before.

I´m coming from Visual Studio Community and trying to migrate to vscode.

Although it might be a solution, probably I´d need to prepare my project somehow, cause it simply won´t work out of the box.

I tried both npm i -g ionic and npm i -g ionic@legacy, and after that the ionic serve command

None worked here for my existing project.

I´d need some time to try to prepare it.

Hopefully there´s an easier workaround available.

**Comment by jwargo** [comment]
What do you mean by prepare it? If its an ionic project, everything you need is already there. Open a terminal window in VS Code (`CTRL ~`) and type in `ionic serve`, that's all there is to it.

**Comment by lhrolim** [comment]
It´s not.

It´s an ionic project, in a sense that it uses ionic, it´s declared on package.json.

Trying Ionic serve I got:  

couldn´t find ionic.config.json

Then I created this file, manually copying from:

https://github.com/ionic-team/ionic-preview-app/blob/master/ionic.config.json

However my index file was called layout.html and hence I got an error saying file couldn´t be found.

I renamed it to index.html, but still getting console errors, saying cordova is not defined.

So clearly there´s some sort of preparation step missing here.

**Comment by jwargo** [comment]
how did you create the project? you didn't create it with the ionic CLI?  VS Code has a debug configuration for `ionic serve` so you can kick this off from within the debugger, not needing to use the CLI from a terminal window.

**Comment by lhrolim** [comment]
It wasn´t created with Ionic CLI. 

Running from VSCode I get:

[cordova-tools] Error processing "launch": Error: Serving to the browser is currently only supported for Ionic projects

Again, I use Ionic1, but never said it was an "ionic project" in a sense that it was created with Ionic CLI.

Your suggestion is good though, but might require me to migrate my project towards that direction.

I´d appreciate, though, if there was an easier way to accomplish a similar result without much hassle.

**Comment by jwargo** [comment]
The extension works with Cordova and Ionic projects created with their respective CLIs. We expect the core project components to be there - that's how we do our stuff under the covers.  It feels like this isn't a usage scenario we can support. I'm sorry.

**Comment by lhrolim** [comment]
Wait, I just want to clarify that the extension does work fine in my project, hence I don´t think this is a matter of how the project was setup in first place.

(Fyi: It was done 2 years ago using VisualStudio´s Cordova Tools extensions)

I´m just trying to understaand why the "cordova-simulate" pane can´t be closed or even, at least, groupped into the main editor (dragged), since having to keep it open next to the code editor reduces drastically the coding experience especially on small monitors.

**Comment by lhrolim** [comment]
Right now, this is how I´d be able to code, but I´d like to get rid of the window at the right, if possible.

I´m trying to debug the code a bit, but no luck so far to understaand it. 
It seems to close the socket if the window gets closed, but not sure yet.

![image](https://user-images.githubusercontent.com/53955/32785511-e0d4dbf6-c938-11e7-885f-15c6818ac5cb.png)

**Comment by jwargo** [comment]
OK, so the team that built this extension is a different team than the one that built TACO, and I'm not sure if anything was done to make the two interoperable. When you simulate in browser using TACO, it launches Cordova Simulate which opens two browser windows: one for the Cordova Simulate and the other for the simulated app. When it does this, it automatically enables live reload, so any changes to your app's HTML will automatically be reflected in the simulated app when you save your changes in the editor. I'm not sure exactly what happens when you close the Cordova Simulate window, but it breaks that connection to the simulated app in the browser, hence your inability to refresh from there.

What I suggest you do is upgrade the project to an Ionic 3 project, then use the Ionic serve capabilities in the Visual Studio Code extension - that will give you the ability to test your app in the browser while eliminating the Cordova Simulate window you don't want to be there. however, that will break your ability to test capabilities exposed by any core Cordova plugins you have in your project.

**Comment by lhrolim** [comment]
@jwargo thanks for clarifying it a bit further.

Migrating to me isn´t an easy thing to do, since I´d need to migrate angularjs to angular first, and I do have a large codebase.

It seems like the extension is working fine with TACO projects, except for that little inconvenient window that can´t be closed/minimized, etc. 

It seems to be not even a matter of purely refreshing it, but the whole cordova deviceready event isn´t sent anymore if the window isn´t visible.

Wouldn´t it make sense, in general,  to allow minimizing it, or grouping it to the main editor? Is it somewhat feasible?  I could try to contribute, if you point me towards a bit.

Cause to me it sounds like it´s 95% in the way of being usable.

To be honest, if there´s no solution even with that window out there, I´m considering switching from VSCommunity2017 to VSCode due to the benefits of it.

**Comment by jwargo** [comment]
I'm pretty sure that's because the deviceReady event doesn't fire in the browser - there's no Cordova container to trigger it. Remember, you're simulating a mobile platform (Android, iOS, etc.) in the browser, so I imagine that the Cordova Simulate window is firing it for you in order to simulate an actual device.  You could validate this by looking at the Cordova Simulate code at https://github.com/Microsoft/cordova-simulate.

**Comment by lhrolim** [comment]
I was checking first the extension code. Perhaps you can help me with it.

There´s clearly some sort of integration with cordova-simulate, since it declares it on package.json.

Also, at PluginSimulator.ts there are references to it.

Following the instructions at the site I was able to put some breakpoints at the CordovaDebugAdapter.ts to play around for a bit.

However, I cannot modify/stop  at the PluginSimulator.ts. 

I´m just curious, but I also do not have any expertise at VSCode extension development.

How do I modify the simulate.ts file, or why aren´t my breakpoints hit out there?

**Comment by jwargo** [comment]
No, sorry; you've reached the limits of my capabilities; I'm just the PM for the extension, not one of the developers. 

Cordova Simulate is invoked by the Visual Studio Code extension, not actual source code for your app. That's why you can't breakpoint it.

I've not looked at the extension code, but I imagine the extension is executing the `simulate` command which fires up Cordova Simulate as a separate process - this isn't something you can debug, at least not from within an ionic app.  Visual Studio Code includes capabilities you can use to debug an extension, but that won't even help here as Cordova Simulate is external to the extension (as I understand it).

**Comment by lhrolim** [comment]
@jwargo  thanks. I´ll keep digging as a hobby later.

**Comment by jwargo** [comment]
OK, good luck. Closing this issue.

**Comment by lhrolim** [comment]
@jwargo  as a last remark, although you closed it already:

I can´t believe I´m the first one complaining about this. To me it still does sound like something to be solved in a way or another to allow the extension to work flawlessly with ionic 1 projects.

**Comment by jwargo** [comment]
I'm not sure if its come up before, I'm only three months at Microsoft. I think if the devs hopped on this conversation, they'd probably say that we only support Ionic 2 and 3 projects. there's only so much we can do from a backward compatibility standpoint. I'll ask whether we considered supporting an app that was created with TACO, and find out what I can from there.

**Comment by lhrolim** [comment]
@jwargo Cool. 
I understaand your point about backwards compatibility.

I´d totally get it if the extension wasn´t working at all, which isn´t the case. It does work fine, except for that little incovenient window at the right. 

If that could be opened as a second brower window perhaps, instead of an embedded vscode window it would also do the trick.

I do consider it a minor thing though, indeed.

I setup vscode here to wrap the words and I´m able to develop with that little window minimized at the right and it´s lighter (and hence better) than VSCommunity.

**Comment by pniko** [comment]
@svekl @iTOYS - can you two look into @lhrolim's issue on this thread?

**Comment by iTOYS** [comment]
Hi @lhrolim,
You can just drag `/cordova-simulate` tab in first view column and switch tabs if needed.
This should help you.

**Comment by lhrolim** [comment]
Ti @iTOYS  indeed that would be ideal. 

However, If the tab is not visible it simply stops the livereload anyway.

If only the tab could stay there groupped as you suggested but keeping cordova events working it would do the trick.

**Comment by iTOYS** [comment]
One more trick for you)
Open in your browser:
`http://localhost:<port>/simulator/index.html`
Where <port> it's port from launch.json configuration(default: 8000)
And then you can close tab in vscode

**Comment by lhrolim** [comment]
@iTOYS 

Awesome, that last tip was surely effective!

From a Product standpoint, my humble suggestion is that maybe there could be some sort of parameter to lauch the emulator like this (although I still think 100% of the developers would prefer it like that, or as a closeable tab from your original suggestion)

Thanks

**Comment by jwargo** [comment]
@iTOYS Nice!  Thanks for that.

**Comment by iTOYS** [comment]
@lhrolim 

Thanks for suggestion!
I'll try do something with it.

**Comment by iTOYS** [comment]
Fixes #349
