### ISSUE TITLE
How to disable cordova plugin

### ISSUE THREAD

**Issue by lokinfey** [Microsoft/vscode-cordova#35]
I can use cordova with Visual Studio Plugin . But When I create nodejs project not cordova  , I build (cmd+shit +b in my mac ), it can not compile well . just like this
<img width="717" alt="2016-02-04 11 54 15" src="https://cloud.githubusercontent.com/assets/4607663/12820577/a310eda2-cb9a-11e5-823f-e835d2272e8b.png"> How can I disable the plugin when it is not cordova project ?

**Comment by meenakb** [comment]
Apologies for this issue! Our next update will have a fix for this (we will be using the F6 shortcut instead of cmd+shift+b).

For now, you can customize the shortcut. In VS Code, go to File -> Preferences -> "Keyboard shortcuts" and add the following to the keybindings.json file that opens up in the right-side of the split editor.
[
    { "key": "ctrl+shift+b",          "command": "workbench.action.tasks.build" }
]

This will make sure that your configured build task is invoked as you would expect.

**Comment by meenakb** [comment]
Closing the issue. Let us know if you have further questions.
