### ISSUE TITLE
Upgrade to VS Code's webview API

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-cordova#447]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by mjbvz** [comment]
1. Can you provide some example paths? `file://` resources definitely will not work using the webview api but local resources generally should inside an iframe

2. Unsure. We don't explicitly block this but we have better isolated webview content

**Comment by SounD120** [comment]
Hi @mjbvz , thanks for your reply. Seems to be that WebView API breaks us completely, but, fortunately, we have a workaround for this scenario and we are going to propose a PR for it soon. We will keep you posted about the progress.

**Comment by SounD120** [comment]
Hi @mjbvz, we [removed previewHtml from our code](https://github.com/Microsoft/vscode-cordova/pull/452), but we couldn't use Webview API instead due to incompatibility with the specific scenario we have. We used previewHtml for rendering localhost server page, but it is not allowed by WebView API, so we had to launch it in a browser instead. We are going to include this change in the mext major release. Thanks again for warning us about the potential problem we could have faced with.
