### ISSUE TITLE
Unable to communicate with target

### ISSUE THREAD

**Issue by SpellCraft** [Microsoft/vscode-cordova#477]
## Actual Behavior
1. Spams the console with "Unable to communicate with target" before ending with "unable to find webview"

## Expected Behavior
1. Be able to debug cordova project through vscode when "Run iOS on device" is selected.

## Software versions
- Cordova VS Code extension version: 1.6.1
- VSCode version: 1.30.2
- OS platform and version: iOS 10.0+
- NodeJS version: 11.6.0
- Cordova version: 8.1.2
- Cordova-Android/iOS/Windows version: cordova-ios@4.5.5

To even be able to get to this point, I had to follow some of the steps in this issue here: 465#issuecomment-448156409

I'm not sure what to do beyond this. It feels like I have tried everything.

**Comment by SounD120** [comment]
Hi @SpellCraft . Thanks for contacting us. This error means that `ios-webkit-debug-proxy` is not being ran or being worked with errors, so extension is unable to perform get request to proxy server. You mentioned that you have tried some of the steps from https://github.com/Microsoft/vscode-cordova/issues/465#issuecomment-448156409 , but in order to get it work you need to do them all. Please do them and then try to run `ios-webkit-debug-proxy` manually in terminal and copy output from the `ios-webkit-debug-proxy` here.

**Comment by SpellCraft** [comment]
Hello!
Yeah, I followed the comment in its entirety.

```bash
Last login: Tue Jan 15 13:56:38 on console
Arnts-MBP:~ arntpedersen$ ios-webkit-debug-proxy
-bash: ios-webkit-debug-proxy: command not found
Arnts-MBP:~ arntpedersen$ brew install ios-webkit-debug-proxy
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
phpunit

Warning: ios-webkit-debug-proxy 1.8.3 is already installed and up-to-date
To reinstall 1.8.3, run `brew reinstall ios-webkit-debug-proxy`
```

That´s the output I´m getting right now.

**Comment by SounD120** [comment]
@SpellCraft Sorry for confusing a bit, `ios_webkit_debug_proxy` is the command for IWDP.

**Comment by SpellCraft** [comment]
Excuse the late reply. I went off to lunch right before the message!

Using the command you provided above, I apparently had to go into Safari's advance settings and enable network inspection.

Doing that seems to have solved my problem! Thank you for your guidance. :)
