### ISSUE TITLE
[cordova-tools] Debugging "Simulate iOS in browser" not live reloading on code change

### ISSUE THREAD

**Issue by 1housand** [microsoft/vscode-cordova#532]
## Actual Behavior
1. Start debugging in VS Code with configuration "Simulate iOS in browser" from Cordova Tools
2. App launches, but does not live reload on code change or when restart debug
3. But app updates when I run "ionic cordova build ios" and restart the debug

## Expected Behavior
1. Live reloads on code changes

## Software versions
- Cordova VS Code extension version: 1.8.1
- VSCode version: 1.33.1
- OS platform and version: MacOS Mojave 10.14.4
- NodeJS version: 10.15.3
- Cordova version: 9.0.0
- Ionic version: 4.12.0
- App type: Angular

## Outputs (Include if relevant)
- launch.json configuration:
```
{
    "name": "Simulate iOS in browser",
    "type": "cordova",
    "request": "launch",
    "platform": "ios",
    "target": "chrome",
    "simulatePort": 8000,
    "ionicLiveReload": true,
    "cwd": "${workspaceFolder}",
    "sourceMaps": true
}
```

**Comment by ruslan-bikkinin** [comment]
Hi @1housand and thanks for reach us. What ionic version does your project use? What is your type of your app (angular, ionic-angular, ionic1, custom)?

**Comment by 1housand** [comment]
Hi @ruslan-bikkinin. thank you for your help and sorry that I forgot to add that information.
I updated my post with the information you asked. Thanks!

**Comment by ruslan-bikkinin** [comment]
@1housand we have two configuration parameters: `ionicLiveReload` and `livereload`.
The first one is intended for enabling live reload for ionic server while running `Run on device/emulator` and `Ionic serve` scenarios (e.g. it passes "--livereload" option to `ionic serve` and `ionic cordova run` command), the second one is intended for enabling livereload for "Simulate ..." debug scenarios (e.g. is passes `--livereload` option to `simulate` command). If you are running "Simulate... " scenarios for Ionic apps `ionicLiveReload` is not taking any effect. 
To make it work for Ionic 3 angular projects you needed to have `ionic serve --livereload` command running in background in order to compile assets and update www directory and then you could run "Simulate..." scenario with `"livereload" : true` and have a live reload working for your app.
Unfortunately, for Ionic 4 Angular projects that approach doesn't work, because now angular templates uses in-memory assets updates e.g. `www` directory is not updated and `simulate` can't track any changes there.
As soon as possible solution for this is found for `cordova-simulate` package this feature will be available again.
