### ISSUE TITLE
not using typescript sourcemaps when landing on debug breakpoints using cordova extension launch/attach configuration

### ISSUE THREAD

**Issue by myusrn** [Microsoft/vscode-cordova#55]
I'm trying to use vscode cordova extension debug/launch settings on a simple cordova typescript ng2 application, based on https://angular.io/docs/ts/latest/quickstart.html, where the launch/attach settings rely on the vscode marketplace chrome [ http://aka.ms/vscDbgCh ]  and cordova tools [ http://aka.ms/vscDbgCt ] extensions. 

I can get vscode to successfully launch/attach to the ripple [ or android ] emulator session but when it stops on my typescript soft breakpoints its doing so using the transpiler app/*.js output and not the app/*.js.map output that aligns with my original sources.   

This can be repro’d by cloning https://github.com/myusrn/acu6withng2 | opening in vscode | setting a few break points in app/main.ts and/or app.component.ts | then from command line in app1 folder executing "npm install" + "npm run tsc" + "ripple emulate" from app1 folder | then selecting vscode debug | launch | "Launch ripple emulate browser with sourcemaps" option.

Instead of using "ripple emulate" and "launch ripple emulate browser with sourcemaps" option I moved to using "cordova emulate android" and "attach to running android on emulator" which exercises vscode marketplace cordova extension, vs chrome one, and with that i'm getting "Error [cordova-debug-adapter] TypeError: Path must be a string. Received undefined" result.

**Comment by MSLaguana** [comment]
I tried running your project, but ran into issues with ripple so I wasn't able to replicate. However since you are targeting "chrome" in that debug configuration, it is using the vscode-chrome-debugger for everything. Have you looked at https://github.com/Microsoft/vscode-chrome-debug#troubleshooting to see if you have configured things correctly? You may need to force the sourcemaps to include absolute paths for sourceRoot. It looks like your issue is similar to https://github.com/Microsoft/vscode-chrome-debug/issues/85
