### ISSUE TITLE
Restart button when debugging just refreshes the current page without applying changes

### ISSUE THREAD

**Issue by ajuanjojjj** [microsoft/vscode-cordova#685]
## Actual Behavior
1. Run cordova from the extension
2. Change something in the code
3. Click the ♻️ refresh button on the debugger
4. The cordova app just refreshes the current page without applying the change

## Expected Behavior
1. Repeat steps 1, 2, and 3
2. The cordova app either refreshes applying the changes made (Live reload) or recompiles and launches the app

## Software versions
- Cordova VS Code extension version: 2.0.0
- VSCode version: 1.50
- OS platform and version: Windows 10 (10.0.19041 compilation 19041)
- NodeJS version: v12.14.1
- Cordova version: 9.0.0 (cordova-lib@9.0.1)
- Cordova-Android/iOS/Windows version: Not sure

## Notes
This didnt happen in an earlier version of the extension, and instead it just recompiled and launched the app. Given that in order to launch the app from vscode you need to first kill the current debugging session, its quite annoying to have to kill the session, go to the debug tab, and launch the app again

**Comment by ajuanjojjj** [comment]
Reopening as of version 2.1.1

The green restart button "Restart" still refreshes the page (I assume this is now the expected behaviour), but the new "Restart Cordova debugging" blue button throws the warning "There is already a debug configuration "Run Android on device" running." instead of restarting it.

I'm not exactly sure of why this is happening now, i've seen it working a few times before, but i'm happy to try to help locating the error :)

**Comment by RedMickey** [comment]
Hi @ajuanjojjj.
> The green restart button "Restart" still refreshes the page (I assume this is now the expected behaviour)

Yes, now it is the expected behavior, since under the hood the extension uses [`vscode-js-debug` extension](https://github.com/microsoft/vscode-js-debug) for debugging javascript applications. So when you click green `Restart` button VS Code is trying to restart just attach debugging session of `vscode-js-debug` extension instead of the main session of Cordova tools one. That's why we decided to add a special button for restarting the main Cordova tools debugging session

We investigated the issue and found out a probable reason of why VS Code always shows the error notification. It's Ok that in some cases VS Code can show a notification like `There is already a debug configuration...` or `A Cordova application is building now...`. This allows to prevent some issues with debugging sessions. But in our case there was incorrect behavior. I proposed a fix for that in [the PR](https://github.com/microsoft/vscode-cordova/pull/691). Could you please try to install the patched extension VSIX with a fix and let us know how it works for you? To try it please do the following:
* Download and unzip compiled extension VSIX : [cordova-tools-2.1.1.vsix.zip](https://github.com/microsoft/vscode-cordova/files/5536183/cordova-tools-2.1.1.vsix.zip)
* Uninstall the extension
* Close and reopen VS Code
* Install the extension from VSIX:
    * Click `Extensions`
    * Click `...`
    * Click `Install from VSIX...`
    * Select the VSIX file

**Comment by ajuanjojjj** [comment]
Sure thing, although I just came home from work, so I wont be able to do it until monday morning. 

If it's urgent I can try it on my home pc, but i'd have to install the whole environment (SDKs, ADB, node, etc) so i'd prefer to wait if possible.

**Comment by ajuanjojjj** [comment]
Sry for the late response, it's been a busy week;

I've tried the patched extension and it looks all good, with both restart and restart cordova debug buttons working as expected :)

**Comment by RedMickey** [comment]
@ajuanjojjj Glad to hear that. The fix is available in Cordova Tools extension [v2.1.2](https://github.com/microsoft/vscode-cordova/releases/tag/2.1.2). Feel free to reach out to us if you have any questions about the extension.
