### ISSUE TITLE
Simulate Android in Browser not working

### ISSUE THREAD

**Issue by faelv** [microsoft/vscode-cordova#739]
## Actual Behavior
1. Select **Cordova: Simulate Android in Browser**
2. Extensions outputs **cordova-simulate dependency not present. Installing it...**

**cordova-simulate** is installed, if I run `simulate --target=chrome` manually, it works

## Expected Behavior
1. Select **Cordova: Simulate Android in Browser**
2. App opens in browser

## Software versions
- Cordova VS Code extension version: 2.3.0
- VSCode version: 1.60.1
- OS platform and version: Linux Mint 18.4
- NodeJS version: 14.17.6
- Cordova version: 10.0.0
- Cordova-Android/iOS/Windows version: cordova-android 9.1.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
<no output>
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
<no output>
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
<no output>
```

**Comment by RedMickey** [comment]
Hi @faelv and thanks for reaching us.
The extension downloads and installs `cordova-simulate` package locally to the extension's folder and then uses the package for simulating in the browser. Under the hood the extension uses the `npm` command to install this package. So, the problem could be related to use of binaries from the PATH.
Could you please tell us how you installed Node.js (using NVM, snap store, some package managers or a binary file) and VS Code (using snap store or .deb package)?
Could you please also tell us how you launch VS Code: using the UI launcher or in the terminal via `code` command? If you usually use the UI launcher, could you please try to launch VS Code in the terminal using `code` command and then try to run `Cordova: Simulate Android in Browser` extension command again?
Please let us know about your results.

**Comment by faelv** [comment]
Sorry for the delay, I installed npm through nvm, but launching code from terminal actually worked.

**Comment by RedMickey** [comment]
@faelv If VS Code is launched from the terminal, it inherits all environment variables declared in the `.bashrc` (or `.zshrc`) file.  If VS Code is launched by means of the UI launcher, [it inherits environment variables from your profile file instead of rc](https://github.com/microsoft/vscode/issues/53529#issuecomment-402798173).
Could you please check if there is Node.js path in the VS Code process in case it is launched via the UI launcher? 
You can do this the following way:

1. Run VS Code via the UI launcher
2. Open VS Code Development Tools (click "Help" menu item -> Toggle Developer Tools)
3. Open Console and run `console.log(process.env.PATH)` command

This command will show PATH environment variable for VS Code Node.js process context.

If the output string doesn't include Node.js path, could you please check if your `.bash_profile` file (or if it doesn't exist, then `.profile` file) contains the NVM declaration?
```
# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

If there is not the NVM declaration in your profile file, could you please try to add it there and run simulate command again? You can use the steps below:

1. Add the declaration to the `.bash_profile` (`.profile`) file
2. Run `source ~/.bash_profile` command in the terminal (if adding to`.profile`, it's needed to execute log out and log in of the user)
3. Close VS Code and open it again
    3.1 You can also reinstall the extension if the `cordova-simulate` package was already installed previously to make the extension install it again
4. Run `Cordova: Simulate Android in Browser` command

Please let us know about your results.

**Comment by faelv** [comment]
Node was indeed missing from `process.env.PATH`, nvm was being loaded in `.bashrc`, which in turn is being included via `.profile`. Having been using node for quite a while and never had this problem, odd. Anyway, now `cordova-simulate` works when launching vscode via UI launcher. Thanks for the help.

**Comment by RedMickey** [comment]
@faelv I was glad to help you! I’m closing this issue, please feel free to open new ones if needed.
