### ISSUE TITLE
Unable to get device OS version. Details: Command failed: ideviceinfo -s -k ProductVersion

### ISSUE THREAD

**Issue by brunolau** [microsoft/vscode-cordova#756]
## Actual Behavior
1. Unable to debug on iOS device on Mac

## Expected Behavior
1. Debugger attaches and works

## Software versions
- Cordova VS Code extension version:2.4.1
- VSCode version: 1.64.2
- OS platform and version: Mac
- NodeJS version: 16.14.0
- Cordova version: 10.0.0
- Cordova-Android/iOS/Windows version: iOS, 6.2.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[ios-sim] device.name: iPhone 13
[ios-sim] device.runtime: iOS 15.2
device.id: 2DFECC0B-8A87-4D1D-81A4-7054885279B9
[ios-sim] io.cordova.hellocordova: 44378
[ios-sim] logPath: [/Users/bruno/Desktop/com.testapp/platforms/ios/cordova/console.log]()
Simulator successfully started via `ios-sim`.
Unable to get device OS version. Details: Command failed: ideviceinfo -s -k ProductVersion
```

I did all the steps mentioned in the guide, however am unable to start debugging. When running cordova run from the terminal, I receive no error. I've tried with real device, here I'm stuck at Unable to find developer disk image despite having latest iOS and Xcode, so I've tried with simulator and I'm facing this issue. Any help appreciated

**Comment by RedMickey** [comment]
Hi @brunolau and thanks for reaching us. Currently the extension doesn't support iOS simulators due to this https://github.com/microsoft/vscode-cordova/pull/485. We'll investigate whether the [IWDP library](https://github.com/google/ios-webkit-debug-proxy) used under the hood in the extension supports iOS simulators now.

With respect to the error `Unable to find developer disk image` with an iOS device. Could you please check installed dev disk images using the following commands in the terminal?

1. `cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport`
2. List all supported images using  the `ls` command

The output should look something like this:
![image](https://user-images.githubusercontent.com/33267199/154946050-aed4a3a4-aa6f-4b75-9d73-c86eb3641b89.png)

The extension requires the same dev disk image as the iOS version on the device to correctly attach to the app running on the device.

**Comment by brunolau** [comment]
Hi, thanks for help. As of time of opening the issue I couldn't find the developer image for 15.3.1, but found it today, so I've moved one step ahead. Now the app launches, but my breakpoints are not hit. Last 3 lines I see in the output are

Process 1578 detached
Attaching to ios
Configuring debugging proxy

**Comment by RedMickey** [comment]
@brunolau, could you please check if the `Safari Web Inspector` option is enabled on your device?
To reach the `Web Inspector` option you can do the following:
```
Tap Settings > Safari > Advanced
```

If the option is disabled, activate it and try to debug the app again.

If this option is enabled, could you please try to open the URL `http://localhost:9220/json` (port 9220 is the default port specified in the debug configuration) in your browser while the extension hangs on the `Configuring debugging proxy` step and send us the content? This URL should return the list of connected devices. It will help us to understand whether IWDP was able to recognize your device.

**Comment by brunolau** [comment]
Hope I got your instructions correct, I'm unable to connect

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15102770/155146682-7518501c-970e-4847-9e7c-07070b039346.png">

**Comment by brunolau** [comment]
Also the part "Attaching to iOS"takes considerably long time (1-2 min)

**Comment by RedMickey** [comment]
@brunolau It seems that the issue could be in launching iOS WebKit Debug Proxy, which is used by the extension to interact with applications running on iOS devices. Could you please try to do the following steps to check iOS WebKit Debug Proxy work:

1. In the terminal launch your application on an iOS device, the extension uses this command `cordova run ios --device --buildFlag=-UseModernBuildSystem=0` to run the iOS app
2. Run IWDP using the command `ios_webkit_debug_proxy -c null:9220,:9223-9322` in the terminal
3. Try to open the URL `http://localhost:9220/json` in the browser on your computer

If the iOS WebKit Debug Proxy works fine, you should get similar results:
 
![image](https://user-images.githubusercontent.com/33267199/155165094-79b5aa2d-c781-458d-a973-ecae73d6aace.png)
![image](https://user-images.githubusercontent.com/33267199/155164955-0ef06b70-c7f4-4101-831b-a5a3c37d2a8b.png)


> Also the part "Attaching to iOS"takes considerably long time (1-2 min).

I figured out a possible reason of poor performance at this step, we'll try to fix the performance issue.

**Comment by brunolau** [comment]
This is what I got

Listing devices on :9220
Connected :9223 to xxx iPhone (xxx)
ssl recv failed: Undefined error: 0
Disconnected :9223 from xxx iPhone (xxx)

**Comment by RedMickey** [comment]
@brunolau, It seems that there is a problem with establishing secure ssl connection to an iOS device. Since the problem is reproduced in the terminal, this could be an issue of [iOS WebKit Debug Proxy](https://github.com/google/ios-webkit-debug-proxy) library. We tried to reproduce the problem on several devices, but IWDP worked fine on our side.
Could you please open an issue in [iOS WebKit Debug Proxy repository](https://github.com/google/ios-webkit-debug-proxy) about this incorrect behavior? Please attach to the issue verbose logs of IWDP. To run IWDP with verbose logs you can use the following command:

```
ios_webkit_debug_proxy -c null:9220,:9223-9322 -d
```

**Comment by RedMickey** [comment]
@brunolau, It seems that there is a problem with establishing secure ssl connection to an iOS device. Since the problem is reproduced in the terminal, this could be an issue of [iOS WebKit Debug Proxy](https://github.com/google/ios-webkit-debug-proxy) library. We tried to reproduce the problem on several devices, but IWDP worked fine on our side.
Could you please open an issue in [iOS WebKit Debug Proxy repository](https://github.com/google/ios-webkit-debug-proxy) about this incorrect behavior? Please attach to the issue verbose logs of IWDP. To run IWDP with verbose logs you can use the following command:

```
ios_webkit_debug_proxy -c null:9220,:9223-9322 -d
```

**Comment by RedMickey** [comment]
@brunolau, It seems that there is a problem with establishing secure ssl connection to an iOS device. Since the problem is reproduced in the terminal, this could be an issue of [iOS WebKit Debug Proxy](https://github.com/google/ios-webkit-debug-proxy) library. We tried to reproduce the problem on several devices, but IWDP worked fine on our side.
Could you please open an issue in [iOS WebKit Debug Proxy repository](https://github.com/google/ios-webkit-debug-proxy) about this incorrect behavior? Please attach to the issue verbose logs of IWDP. To run IWDP with verbose logs you can use the following command:

```
ios_webkit_debug_proxy -c null:9220,:9223-9322 -d
```
